# Introduction

The data was gathered around May 2019, utilizing the Steam Store and SteamSpy APIs, as stated by the dataset's author on the description.

This is an exploratory analysis of this dataset, mainly utilizing Pandas and its functions. I will try to answer the following questions:

- Top 20 games with the most positive ratings
- Top 20 games with the most negative ratings
- Top 20 games with the highest average playtime
- Price analysis
- Distribution of genres
- Publishers with the highest number of games
- Games released by year
- What does ownership look like

In [5]:
#import libraries
import pandas as pd

## **Initial Dataset Examination**

In [8]:
df = pd.read_csv(r"C:\Users\Mahmoud Ashraf\ieee-jupyter\task12\steam.csv")

In [10]:
df

appid                        name release_date  english  \
0           10              Counter-Strike   2000-11-01        1   
1           20       Team Fortress Classic   1999-04-01        1   
2           30               Day of Defeat   2003-05-01        1   
3           40          Deathmatch Classic   2001-06-01        1   
4           50   Half-Life: Opposing Force   1999-11-01        1   
...        ...                         ...          ...      ...   
27070  1065230             Room of Pandora   2019-04-24        1   
27071  1065570                   Cyber Gun   2019-04-23        1   
27072  1065650            Super Star Blast   2019-04-24        1   
27073  1066700  New Yankee 7: Deer Hunters   2019-04-17        1   
27074  1069460                   Rune Lord   2019-04-24        1   

                developer             publisher          platforms  \
0                   Valve                 Valve  windows;mac;linux   
1                   Valve                 Valve  windows;mac;linux   
2                   Valve                 Valve  windows;mac;linux   
3                   Valve                 Valve  windows;mac;linux   
4        Gearbox Software                 Valve  windows;mac;linux   
...                   ...                   ...                ...   
27070         SHEN JIAWEI           SHEN JIAWEI            windows   
27071      Semyon Maximov      BekkerDev Studio            windows   
27072         EntwicklerX           EntwicklerX            windows   
27073  Yustas Game Studio  Alawar Entertainment        windows;mac   
27074    Adept Studios GD  Alawar Entertainment        windows;mac   

       required_age                                         categories  \
0                 0  Multi-player;Online Multi-Player;Local Multi-P...   
1                 0  Multi-player;Online Multi-Player;Local Multi-P...   
2                 0              Multi-player;Valve Anti-Cheat enabled   
3                 0  Multi-player;Online Multi-Player;Local Multi-P...   
4                 0  Single-player;Multi-player;Valve Anti-Cheat en...   
...             ...                                                ...   
27070             0                   Single-player;Steam Achievements   
27071             0                                      Single-player   
27072             0  Single-player;Multi-player;Co-op;Shared/Split ...   
27073             0                          Single-player;Steam Cloud   
27074             0                          Single-player;Steam Cloud   

                       genres                 steamspy_tags  achievements  \
0                      Action        Action;FPS;Multiplayer             0   
1                      Action        Action;FPS;Multiplayer             0   
2                      Action  FPS;World War II;Multiplayer             0   
3                      Action        Action;FPS;Multiplayer             0   
4                      Action             FPS;Action;Sci-fi             0   
...                       ...                           ...           ...   
27070  Adventure;Casual;Indie        Adventure;Indie;Casual             7   
27071  Action;Adventure;Indie        Action;Indie;Adventure             0   
27072     Action;Casual;Indie           Action;Indie;Casual            24   
27073  Adventure;Casual;Indie        Indie;Casual;Adventure             0   
27074  Adventure;Casual;Indie        Indie;Casual;Adventure             0   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
0                124534              3339             17612              317   
1                  3318               633               277               62   
2                  3416               398               187               34   
3                  1273               267               258              184   
4                  5250               288               624              415   
...                 ...               ...               .

Getting a summary of the statistics in my dataset

In [12]:
df.describe()

appid       english  required_age  achievements  \
count  2.707500e+04  27075.000000  27075.000000  27075.000000   
mean   5.962035e+05      0.981127      0.354903     45.248864   
std    2.508942e+05      0.136081      2.406044    352.670281   
min    1.000000e+01      0.000000      0.000000      0.000000   
25%    4.012300e+05      1.000000      0.000000      0.000000   
50%    5.990700e+05      1.000000      0.000000      7.000000   
75%    7.987600e+05      1.000000      0.000000     23.000000   
max    1.069460e+06      1.000000     18.000000   9821.000000   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
count      2.707500e+04      27075.000000      27075.000000      27075.00000   
mean       1.000559e+03        211.027147        149.804949        146.05603   
std        1.898872e+04       4284.938531       1827.038141       2353.88008   
min        0.000000e+00          0.000000          0.000000          0.00000   
25%        6.000000e+00          2.000000          0.000000          0.00000   
50%        2.400000e+01          9.000000          0.000000          0.00000   
75%        1.260000e+02         42.000000          0.000000          0.00000   
max        2.644404e+06     487076.000000     190625.000000     190625.00000   

              price  
count  27075.000000  
mean       6.078193  
std        7.874922  
min        0.000000  
25%        1.690000  
50%        3.990000  
75%        7.190000  
max      421.990000

Verifying how many lines and columns my dataset has

In [16]:
df.shape

(27075, 18)

Checking if there are any null values in my dataframe. This is good practice, although this dataset was already cleaned by the author.

In [20]:
df.isna().sum()

appid                0
name                 0
release_date         0
english              0
developer            1
publisher           14
platforms            0
required_age         0
categories           0
genres               0
steamspy_tags        0
achievements         0
positive_ratings     0
negative_ratings     0
average_playtime     0
median_playtime      0
owners               0
price                0
dtype: int64

Columns appid and steamspy_tags will be dropped. The former because it doesn't have any relevant information for this exploratory analysis, and the latter because it has very similar data to the genres column, and that is the chosen column to be used in this analysis.

In [22]:
df.drop(columns=['appid','steamspy_tags'])

name release_date  english           developer  \
0                  Counter-Strike   2000-11-01        1               Valve   
1           Team Fortress Classic   1999-04-01        1               Valve   
2                   Day of Defeat   2003-05-01        1               Valve   
3              Deathmatch Classic   2001-06-01        1               Valve   
4       Half-Life: Opposing Force   1999-11-01        1    Gearbox Software   
...                           ...          ...      ...                 ...   
27070             Room of Pandora   2019-04-24        1         SHEN JIAWEI   
27071                   Cyber Gun   2019-04-23        1      Semyon Maximov   
27072            Super Star Blast   2019-04-24        1         EntwicklerX   
27073  New Yankee 7: Deer Hunters   2019-04-17        1  Yustas Game Studio   
27074                   Rune Lord   2019-04-24        1    Adept Studios GD   

                  publisher          platforms  required_age  \
0                     Valve  windows;mac;linux             0   
1                     Valve  windows;mac;linux             0   
2                     Valve  windows;mac;linux             0   
3                     Valve  windows;mac;linux             0   
4                     Valve  windows;mac;linux             0   
...                     ...                ...           ...   
27070           SHEN JIAWEI            windows             0   
27071      BekkerDev Studio            windows             0   
27072           EntwicklerX            windows             0   
27073  Alawar Entertainment        windows;mac             0   
27074  Alawar Entertainment        windows;mac             0   

                                              categories  \
0      Multi-player;Online Multi-Player;Local Multi-P...   
1      Multi-player;Online Multi-Player;Local Multi-P...   
2                  Multi-player;Valve Anti-Cheat enabled   
3      Multi-player;Online Multi-Player;Local Multi-P...   
4      Single-player;Multi-player;Valve Anti-Cheat en...   
...                                                  ...   
27070                   Single-player;Steam Achievements   
27071                                      Single-player   
27072  Single-player;Multi-player;Co-op;Shared/Split ...   
27073                          Single-player;Steam Cloud   
27074                          Single-player;Steam Cloud   

                       genres  achievements  positive_ratings  \
0                      Action             0            124534   
1                      Action             0              3318   
2                      Action             0              3416   
3                      Action             0              1273   
4                      Action             0              5250   
...                       ...           ...               ...   
27070  Adventure;Casual;Indie             7                 3   
27071  Action;Adventure;Indie             0                 8   
27072     Action;Casual;Indie            24                 0   
27073  Adventure;Casual;Indie             0                 2   
27074  Adventure;Casual;Indie             0                 4   

       negative_ratings  average_playtime  median_playtime             owners  \
0                  3339             17612              317  10000000-20000000   
1                   633               277               62   5000000-10000000   
2                   398               187               34   5000000-10000000   
3                   267               258              184   5000000-10000000   
4                   288               624              415   5000000-10000000   
...                 ...               ...              ...                ...   
27070                 0                 0                0            0-20000   
27071                 1                 0                0            0-20000   
27072                 1                 0                0            0-20000   

Altering the genres column inplace. Since this column has many genres separated by semicolons, we will disregard the ones that come after the first and consider that the main genre.

In [42]:
df['genres'].str.split(';').str[0]

0           Action
1           Action
2           Action
3           Action
4           Action
           ...    
27070    Adventure
27071       Action
27072       Action
27073    Adventure
27074    Adventure
Name: genres, Length: 27075, dtype: object

There's a lot of zeroes in the column required_age, so a query is run to check whether that is the situation for the entire column or not, in case it's bad data

In [46]:
(df['required_age']==0).sum()

26479

## **Top 20 Games with the Most Positive Ratings**

Discovering the top 20 games with the most positive reviews on Steam. First, the 20 largest values in the positive_ratings column will be filtered.

In [66]:
df.groupby('name').positive_ratings.max().sort_values(ascending=False).head(20)

name
Counter-Strike: Global Offensive    2644404
Dota 2                               863507
Team Fortress 2                      515879
PLAYERUNKNOWN'S BATTLEGROUNDS        496184
Garry's Mod                          363721
Grand Theft Auto V                   329061
PAYDAY 2                             308657
Unturned                             292574
Terraria                             255600
Left 4 Dead 2                        251789
Tom Clancy's Rainbow Six® Siege      251178
Rocket League®                       242561
The Elder Scrolls V: Skyrim          237303
Warframe                             226541
Rust                                 220370
The Witcher® 3: Wild Hunt            202930
Euro Truck Simulator 2               176769
Paladins®                            169580
ARK: Survival Evolved                145035
Borderlands 2                        144595
Name: positive_ratings, dtype: int64

Then, a query is applied to select only those games whose quantity of positive ratings is above the last number retrieved in the filter. In this case, that would be 144595.

In [88]:
filter = df.positive_ratings >144595
df[filter]

appid                              name release_date  english  \
19        440                   Team Fortress 2   2007-10-10        1   
21        550                     Left 4 Dead 2   2009-11-19        1   
22        570                            Dota 2   2013-07-09        1   
25        730  Counter-Strike: Global Offensive   2012-08-21        1   
121      4000                       Garry's Mod   2006-11-29        1   
1025    72850       The Elder Scrolls V: Skyrim   2011-11-10        1   
1120   105600                          Terraria   2011-05-16        1   
1467   218620                          PAYDAY 2   2013-08-13        1   
1596   227300            Euro Truck Simulator 2   2012-10-12        1   
1634   230410                          Warframe   2013-03-25        1   
2016   252490                              Rust   2018-02-08        1   
2031   252950                    Rocket League®   2015-07-07        1   
2478   271590                Grand Theft Auto V   2015-04-13        1   
2964   292030         The Witcher® 3: Wild Hunt   2015-05-18        1   
3362   304930                          Unturned   2017-07-07        1   
4712   346110             ARK: Survival Evolved   2017-08-27        1   
5235   359550   Tom Clancy's Rainbow Six® Siege   2015-12-01        1   
8129   444090                         Paladins®   2018-05-08        1   
12836  578080     PLAYERUNKNOWN'S BATTLEGROUNDS   2017-12-21        1   

                                               developer  \
19                                                 Valve   
21                                                 Valve   
22                                                 Valve   
25                       Valve;Hidden Path Entertainment   
121                                    Facepunch Studios   
1025                               Bethesda Game Studios   
1120                                            Re-Logic   
1467                     OVERKILL - a Starbreeze Studio.   
1596                                        SCS Software   
1634                                    Digital Extremes   
2016                                   Facepunch Studios   
2031                                       Psyonix, Inc.   
2478                                      Rockstar North   
2964                                      CD PROJEKT RED   
3362                               Smartly Dressed Games   
4712   Studio Wildcard;Instinct Games;Efecto Studios;...   
5235                                    Ubisoft Montreal   
8129                                     Evil Mojo Games   
12836                                   PUBG Corporation   

                      publisher          platforms  required_age  \
19                        Valve  windows;mac;linux             0   
21                        Valve  windows;mac;linux             0   
22                        Valve  windows;mac;linux             0   
25                        Valve  windows;mac;linux             0   
121                       Valve  windows;mac;linux             0   
1025         Bethesda Softworks            windows            16   
1120                   Re-Logic  windows;mac;linux             0   
1467   Starbreeze Publishing AB      windows;linux            18   
1596               SCS Software  windows;mac;linux             0   
1634           Digital Extremes            windows            16   
2016          Facepunch Studios        windows;mac            18   
2031              Psyonix, Inc.  windows;mac;linux             0   
2478             Rockstar Games            windows            18   
2964             CD PROJEKT RED            windows             0   
3362      Smartly Dressed Games  windows;mac;linux             0   
4712            Studio Wildcard  windows;mac;linux             0   
5235                    Ubisoft            windows             0   
8129             Hi-Rez Studios            windows             0   
12836          PUBG Corporation            windows    

Unsurprisingly, the podium is occupied by the wildly popular PC games Counter-Strike: Global Offensive, Dota 2 and Team Fortress 2, all three developed by Steam's own parent company, Valve Software.

## **Top 20 Games with the Most Negative Ratings**

Now, going to the opposite end, discovering the top 20 games with the most negative reviews on Steam. Filtering for the the 20 largest values in the negative_ratings column.

In [90]:
df.groupby('name').negative_ratings.max().sort_values(ascending=False).head(20)

name
PLAYERUNKNOWN'S BATTLEGROUNDS       487076
Counter-Strike: Global Offensive    402313
Dota 2                              142079
Grand Theft Auto V                  139308
Z1 Battle Royale                     91664
DayZ                                 77169
ARK: Survival Evolved                66603
Tom Clancy's Rainbow Six® Siege      59620
PAYDAY 2                             56523
No Man's Sky                         56488
Rust                                 53709
Fallout 4                            45377
Dead by Daylight                     44985
MONSTER HUNTER: WORLD                35294
Heroes & Generals                    34416
Team Fortress 2                      34036
Paladins®                            32407
Unturned                             31482
Robocraft                            30987
FOR HONOR™                           25920
Name: negative_ratings, dtype: int64

Applying a query to select only those games whose quantity of negative ratings is above the last number retrieved in the filter, 25920.

In [92]:
filter =df.negative_ratings>25920
df[filter]

appid                              name release_date  english  \
19        440                   Team Fortress 2   2007-10-10        1   
22        570                            Dota 2   2013-07-09        1   
25        730  Counter-Strike: Global Offensive   2012-08-21        1   
1467   218620                          PAYDAY 2   2013-08-13        1   
1506   221100                              DayZ   2018-12-13        1   
1607   227940                 Heroes & Generals   2016-10-18        1   
2016   252490                              Rust   2018-02-08        1   
2478   271590                Grand Theft Auto V   2015-04-13        1   
2563   275850                      No Man's Sky   2016-08-12        1   
3251   301520                         Robocraft   2017-08-24        1   
3362   304930                          Unturned   2017-07-07        1   
4712   346110             ARK: Survival Evolved   2017-08-27        1   
5235   359550   Tom Clancy's Rainbow Six® Siege   2015-12-01        1   
5916   377160                         Fallout 4   2015-11-09        1   
6046   381210                  Dead by Daylight   2016-06-14        1   
7809   433850                  Z1 Battle Royale   2018-02-28        1   
8129   444090                         Paladins®   2018-05-08        1   
12836  578080     PLAYERUNKNOWN'S BATTLEGROUNDS   2017-12-21        1   
12965  582010             MONSTER HUNTER: WORLD   2018-08-09        1   

                                               developer  \
19                                                 Valve   
22                                                 Valve   
25                       Valve;Hidden Path Entertainment   
1467                     OVERKILL - a Starbreeze Studio.   
1506                                 Bohemia Interactive   
1607                                           RETO MOTO   
2016                                   Facepunch Studios   
2478                                      Rockstar North   
2563                                         Hello Games   
3251                                             Freejam   
3362                               Smartly Dressed Games   
4712   Studio Wildcard;Instinct Games;Efecto Studios;...   
5235                                    Ubisoft Montreal   
5916                               Bethesda Game Studios   
6046                              Behaviour Digital Inc.   
7809                                               NantG   
8129                                     Evil Mojo Games   
12836                                   PUBG Corporation   
12965                                   CAPCOM Co., Ltd.   

                      publisher          platforms  required_age  \
19                        Valve  windows;mac;linux             0   
22                        Valve  windows;mac;linux             0   
25                        Valve  windows;mac;linux             0   
1467   Starbreeze Publishing AB      windows;linux            18   
1506        Bohemia Interactive            windows            18   
1607                  RETO MOTO            windows             0   
2016          Facepunch Studios        windows;mac            18   
2478             Rockstar Games            windows            18   
2563                Hello Games            windows             0   
3251                    Freejam  windows;mac;linux             0   
3362      Smartly Dressed Games  windows;mac;linux             0   
4712            Studio Wildcard  windows;mac;linux             0   
5235                    Ubisoft            windows             0   
5916         Bethesda Softworks            windows            18   
6046     Behaviour Digital Inc.            windows             0   
7809      Daybreak Game Company            windows             0   
8129             Hi-Rez Studios            windows             0   
12836          PUBG Corporation            windows             0   
12965          CAPCOM Co., Ltd.            windows    

Popular video games, especially those with live-service and multiplayer components, can often be very divisive or controversial due to the fickle nature of the player bases and the state of their satisfaction or dissatisfaction with the games as they get updated and changed. Thus Counter-Strike: Global Offensive and Dota 2 occupy 2 of the 3 spots of games with the most negative reviews.

## **Top 20 Games with the Highest Average Playtime**

Taking a look at how much time people spend on Steam's most popular games, on average.

First, the average_playtime column will be converted from minutes to hours for better visualization

In [94]:
df['average_playtime'] = df['average_playtime'] / 60

In [96]:
df.groupby('name').average_playtime.max().sort_values(ascending=False).head(20)

name
The Abbey of Crime Extensum                3177.083333
The Banner Saga: Factions                  1587.416667
The Secret of Tremendous Corporation       1587.366667
PRICE                                      1058.016667
Boundless                                   920.066667
Shroud of the Avatar: Forsaken Virtues      910.300000
X-Plane 11                                  736.150000
懒人修仙传                                       727.200000
Fantasy Grounds                             717.900000
Screeps                                     646.750000
The Price of Freedom                        600.483333
FINAL FANTASY XIV Online                    481.616667
Darkstone                                   456.250000
Warp Rider                                  422.066667
Trivia Vault: Science & History Trivia      422.033333
The Moon Night                              421.950000
Dota 2                                      399.066667
PLAYERUNKNOWN'S BATTLEGROUNDS               382.300000
Count

## **Price Analysis**

A simple price analysis will be shown below, focusing on the split of free vs. paid games, average price by year and general price distribution. 

release_year and release_month columns will be created from the release_date one, as it will be used for this price analysis and a few other metrics down the line

In [116]:
df['release_date']=pd.to_datetime(df['release_date'])
df['month'] = df['release_date'].dt.month
df['year'] = df['release_date'].dt.year
df['price'].count() # number of free games.
df.groupby('year').price.mean() # the avg price per year

year
1997    5.990000
1998    7.190000
1999    3.990000
2000    5.590000
2001    1.995000
2002    7.990000
2003    2.993333
2004    5.758333
2005    4.026667
2006    7.558542
2007    5.633011
2008    6.535241
2009    6.990393
2010    7.388866
2011    7.527824
2012    8.588563
2013    8.694737
2014    7.462797
2015    6.419072
2016    5.893765
2017    5.891822
2018    5.565001
2019    6.191536
Name: price, dtype: float64

A new boolean column will be added called free, this column displays whether a game is free or paid

In [120]:
df['free'] = df['price'] >0
df['free']

0        True
1        True
2        True
3        True
4        True
         ... 
27070    True
27071    True
27072    True
27073    True
27074    True
Name: free, Length: 27075, dtype: bool

## **Publishers and Developers with the Highest Number of Games**

In [136]:
df.groupby('publisher').name.count().sort_values(ascending=False).head(20)

publisher
Big Fish Games                212
Strategy First                136
Ubisoft                       111
THQ Nordic                     98
Square Enix                    97
Sekai Project                  96
Choice of Games                94
1C Entertainment               88
Dagestan Technology            88
SEGA                           78
Degica                         77
Plug In Digital                72
KOEI TECMO GAMES CO., LTD.     71
KISS ltd                       71
Slitherine Ltd.                71
AGM PLAYISM                    69
Artifex Mundi                  67
Buka Entertainment             66
Devolver Digital               65
Atriagames                     64
Name: name, dtype: int64

In [138]:
df.groupby('developer').name.count().sort_values(ascending=False).head(20)

developer
Choice of Games               94
KOEI TECMO GAMES CO., LTD.    72
Ripknot Systems               62
Laush Dmitriy Sergeevich      51
Nikita "Ghost_RUS"            50
Dexion Games                  45
RewindApp                     43
Hosted Games                  42
Blender Games                 40
Humongous Entertainment       36
For Kids                      36
EnsenaSoft                    35
Eipix Entertainment           32
Nekyau Games                  32
Warfare Studios               31
HeR Interactive               30
MumboJumbo                    29
ERS G Studios                 28
Creobit                       28
HexWar Games                  27
Name: name, dtype: int64

Top 10 games by ownership

In [142]:
df.sort_values(by='owners', ascending=False).head(10)

appid                              name release_date  english  \
25        730  Counter-Strike: Global Offensive   2012-08-21        1   
12836  578080     PLAYERUNKNOWN'S BATTLEGROUNDS   2017-12-21        1   
258     10180  Call of Duty®: Modern Warfare® 2   2009-11-11        1   
2602   278360            A Story About My Uncle   2014-05-28        1   
903     49520                     Borderlands 2   2012-09-20        1   
1596   227300            Euro Truck Simulator 2   2012-10-12        1   
11791  550650                       Black Squad   2017-07-28        1   
1547   224260              No More Room in Hell   2013-10-31        1   
2964   292030         The Witcher® 3: Wild Hunt   2015-05-18        1   
2502   273110     Counter-Strike Nexon: Zombies   2014-10-07        1   

                                        developer  \
25                Valve;Hidden Path Entertainment   
12836                            PUBG Corporation   
258                     Infinity Ward;Aspyr (Mac)   
2602                             Gone North Games   
903    Gearbox Software;Aspyr (Mac);Aspyr (Linux)   
1596                                 SCS Software   
11791                                   NS STUDIO   
1547                    No More Room in Hell Team   
2964                               CD PROJEKT RED   
2502   Valve Corporation, Nexon Korea Corporation   

                          publisher          platforms  required_age  \
25                            Valve  windows;mac;linux             0   
12836              PUBG Corporation            windows             0   
258          Activision;Aspyr (Mac)        windows;mac             0   
2602        Coffee Stain Publishing  windows;mac;linux             0   
903    2K;Aspyr (Mac);Aspyr (Linux)  windows;mac;linux            18   
1596                   SCS Software  windows;mac;linux             0   
11791                     NS STUDIO            windows             0   
1547                    Lever Games  windows;mac;linux             0   
2964                 CD PROJEKT RED            windows             0   
2502        Nexon Korea Corporation            windows             0   

                                              categories  \
25     Multi-player;Steam Achievements;Full controlle...   
12836             Multi-player;Online Multi-Player;Stats   
258    Single-player;Multi-player;Co-op;Steam Achieve...   
2602   Single-player;Steam Achievements;Full controll...   
903    Single-player;Co-op;Steam Achievements;Full co...   
1596   Single-player;Steam Achievements;Steam Trading...   
11791  Multi-player;Steam Achievements;Steam Trading ...   
1547   Multi-player;Co-op;Cross-Platform Multiplayer;...   
2964   Single-player;Steam Achievements;Full controll...   
2502   Single-player;Multi-player;MMO;Co-op;Steam Ach...   

                                                 genres  ... achievements  \
25                                  Action;Free to Play  ...          167   
12836            Action;Adventure;Massively Multiplayer  ...           37   
258                                              Action  ...           50   
2602                             Adventure;Casual;Indie  ...           15   
903                                          Action;RPG  ...           69   
1596                                   Indie;Simulation  ...           67   
11791                  Action;Free to Play;Early Access  ...           36   
1547                          Action;Free to Play;Indie  ...          107   
2964                                                RPG  ...           78   
2502   Action;Casual;Free to Play;Massively Multiplayer  ...           65   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
25              2644404            402313        374.900000             6502   
12836            496184            487076        382.300000            12434   
258               30006              2826         16.650000              580  